GET https://fetel-rest-api-heart.vercel.app/data


###
POST http://localhost:8080/data
Content-Type: application/json

{
    "name": "",
    "data": 132
}

###
DELETE http://localhost:8080/data/6607065c9bea9f380e86cfd8