GET http://localhost:8080/spo2/

###

GET http://localhost:3000/BPM/66022810abaab35b55055df8


###

POST http://localhost:8080/spo2/
Content-Type: application/json

{
    "name":"spo2",
    "data":324
}

###
DELETE http://localhost:8080/BPM/66051d69066b79906ecc69e6
