GET http://localhost:8080/BPM

###

GET http://localhost:3000/BPM/66022810abaab35b55055df8


###

POST http://localhost:8080/BPM/
Content-Type: application/json

{
    "name":"BPM",
    "data":85
}

###
DELETE http://localhost:3000/BPM/66022810abaab35b55055df8
